# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ABC
spec:
  owner: krupakar
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
annotations:
    github.com/project-slug: Krupakar-debuide/test
metadata:
  name: BCD
spec:
  owner: krupakar
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DEF
  description: This are DEF-Blocks
  tags:
    - java
  links:
  - url: https://github.com/Krupakar-debuide/rcd-workflow
    title: DEF-Github
    icon: dashboard
spec:
  type: BLock
  lifecycle: Live
  system: ABC
  owner: krupakar
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: XYZ
  description: This are XYZ-Blocks
  tags:
    - nodejs
  links:
  - url: https://krupakarreddy-yasa.medium.com
    title: Medium-website
    icon: dashboard
spec:
  type: Workflow
  lifecycle: Live
  system: BCD
  owner: krupakar
